name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-go@v7.0.0
        with:
          go-version: '1.27'
          cache: true
      - name: Install gotask
        uses: go-task/setup-task@v2.2.0
        with:
          version: '3.x'
      - name: Vet
        run: task vet
      - name: Test
        run: task test
      - name: Build
        run: task build
